services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./web:/rails
      - web_bundle:/usr/local/bundle
      - web_storage:/rails/storage

volumes:
  web_bundle:
  web_storage:
